services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: agno-fastapi-azure:dev
    container_name: agno-api-dev
    working_dir: /app
    env_file: .env
    volumes:
      - ./:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    ports:
      - "8080:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health/live || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
