version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: agno-fastapi-azure:prod
    container_name: agno-api
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
